In [1]:
import pandas as pd

In [6]:
df_pokemon = pd.read_excel("pokemon.xlsx")
df_pokemon.sample(2)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
502,503,V,Samurott,Daikenki,water,NaN,Formidable Pokémon,88.1,11.9,1.5,...,Level,Dewott,Level,Samurott,NaN,NaN,NaN,NaN,NaN,"In the time it takes a foe to blink, it can dr..."
238,239,II,Elekid,Elekid,electric,NaN,Electric Pokémon,75.49,24.51,0.6,...,Level,Electabuzz,Trade with Electirizer,Electivire,NaN,NaN,NaN,NaN,NaN,"When a storm approaches, this Pokémon gets res..."

Explicação sobre a Tabela:

- 0: Sem dano (o Pokémon é imune a ataques do tipo Normal).
- 1: Dano normal (nenhum aumento ou redução).
- 2: O dobro do dano (o Pokémon é fraco contra ataques do tipo Normal).
- 3: Triplo do dano.
- 4: Quadruplo do dano.

### Pokémons Fracos em Geral

In [ ]:
weakness_geral_df_pokemon = df_pokemon[(df_pokemon['against_normal' ] >= 2) 
                                       & (df_pokemon['against_fire' ] >= 2)
                                       & (df_pokemon['against_water' ] >= 2)
                                       & (df_pokemon['against_electric' ] <= 2)
                                       & (df_pokemon['against_grass' ] <= 2)
                                       & (df_pokemon['against_ice' ] <= 2)
                                       & (df_pokemon['against_fighting' ] <= 2)
                                       & (df_pokemon['against_poison' ] <= 2)
                                       & (df_pokemon['against_ground' ] <= 2)
                                       & (df_pokemon['against_flying' ] <= 2)
                                       & (df_pokemon['against_psychic' ] <= 2)
                                       & (df_pokemon['against_bug' ] <= 2)
                                       & (df_pokemon['against_rock' ] <= 2)
                                       & (df_pokemon['against_ghost' ] <= 2)
                                       & (df_pokemon['against_dragon' ] <= 2)
                                       & (df_pokemon['against_dark' ] <= 2)
                                       & (df_pokemon['against_steel' ] <= 2)
                                       & (df_pokemon['against_fairy' ] <= 2)]

weakness_geral_df_pokemon[["english_name","primary_type","against_normal","against_fire","against_water","against_electric","against_grass","against_ice","against_fighting","against_poison","against_ground","against_flying","against_psychic","against_bug","against_rock","against_ghost","against_dragon","against_dark","against_steel","against_fairy"]]

### Pokémons Fracos Contra o Tipo Normal

In [24]:

weakest_pokemon_top10 = df_pokemon["against_normal"].nlargest(4)

for idx in weakest_pokemon_top10.index:
    print("Nome do Pokémon:", df_pokemon.loc[idx, "english_name"])
    print("Tipos do Pokémon:", df_pokemon.loc[idx, "primary_type"])
    print("Tipos do Pokémon:", df_pokemon.loc[idx, "secondary_type"])
    print("Valor em against_normal:", df_pokemon.loc[idx, "against_normal"])
    print("\n")

Nome do Pokémon: Bulbasaur
Tipos do Pokémon: grass
Tipos do Pokémon: poison
Valor em against_normal: 1.0


Nome do Pokémon: Ivysaur
Tipos do Pokémon: grass
Tipos do Pokémon: poison
Valor em against_normal: 1.0


Nome do Pokémon: Venusaur
Tipos do Pokémon: grass
Tipos do Pokémon: poison
Valor em against_normal: 1.0


Nome do Pokémon: Charmander
Tipos do Pokémon: fire
Tipos do Pokémon: nan
Valor em against_normal: 1.0

In [34]:
fraquezas_normal_vs_grama = df_pokemon[(df_pokemon['against_water' ] > 2) & (df_pokemon['against_ground' ] > 2)]

fraquezas_normal_vs_grama_sorted = fraquezas_normal_vs_grama.sort_values(by='against_normal', ascending=False)
display(fraquezas_normal_vs_grama_sorted[["english_name", "primary_type", "secondary_type","against_normal"]])

    english_name primary_type secondary_type  against_normal
0      Bulbasaur        grass         poison             1.0
581    Vanillite          ice            NaN             1.0
572     Cinccino       normal            NaN             1.0
573      Gothita      psychic            NaN             1.0
574    Gothorita      psychic            NaN             1.0
..           ...          ...            ...             ...
276      Swellow       normal         flying             1.0
277      Wingull        water         flying             1.0
278     Pelipper        water         flying             1.0
279        Ralts      psychic          fairy             1.0
897      Calyrex      psychic          grass             1.0

[738 rows x 4 columns]

### Pokémons Fracos Contra o Tipo Água

In [25]:

weakest_pokemon_top10 = df_pokemon["against_water"].nlargest(4)

for idx in weakest_pokemon_top10.index:
    print("Nome do Pokémon:", df_pokemon.loc[idx, "english_name"])
    print("Tipos do Pokémon:", df_pokemon.loc[idx, "primary_type"])
    print("Tipos do Pokémon:", df_pokemon.loc[idx, "secondary_type"])
    print("em against_Water:", df_pokemon.loc[idx, "against_water"])
    print("\n")

Nome do Pokémon: Geodude
Tipos do Pokémon: rock
Tipos do Pokémon: ground
em against_Water: 4.0


Nome do Pokémon: Graveler
Tipos do Pokémon: rock
Tipos do Pokémon: ground
em against_Water: 4.0


Nome do Pokémon: Golem
Tipos do Pokémon: rock
Tipos do Pokémon: ground
em against_Water: 4.0


Nome do Pokémon: Onix
Tipos do Pokémon: rock
Tipos do Pokémon: ground
em against_Water: 4.0

### Pokémons Fracos Contra o tipo Elétrico

In [29]:

weakest_pokemon_top10 = df_pokemon["against_electric"].nlargest(4)

for idx in weakest_pokemon_top10.index:
    print("Nome do Pokémon:", df_pokemon.loc[idx, "english_name"])
    print("Tipos do Pokémon:", df_pokemon.loc[idx, "primary_type"])
    print("Tipos do Pokémon:", df_pokemon.loc[idx, "secondary_type"])
    print("Valor em against_electric:", df_pokemon.loc[idx, "against_electric"])
    print("\n")

Nome do Pokémon: Gyarados
Tipos do Pokémon: water
Tipos do Pokémon: flying
Valor em against_electric: 4.0


Nome do Pokémon: Mantine
Tipos do Pokémon: water
Tipos do Pokémon: flying
Valor em against_electric: 4.0


Nome do Pokémon: Wingull
Tipos do Pokémon: water
Tipos do Pokémon: flying
Valor em against_electric: 4.0


Nome do Pokémon: Pelipper
Tipos do Pokémon: water
Tipos do Pokémon: flying
Valor em against_electric: 4.0

### Pokémons Fracos Contra o Tipo Grama

In [26]:

weakest_pokemon_top10 = df_pokemon["against_grass"].nlargest(4)

for idx in weakest_pokemon_top10.index:
    print("Nome do Pokémon:", df_pokemon.loc[idx, "english_name"])
    print("Tipos do Pokémon:", df_pokemon.loc[idx, "primary_type"])
    print("Tipos do Pokémon:", df_pokemon.loc[idx, "secondary_type"])
    print("Valor em against_grass", df_pokemon.loc[idx, "against_grass"])
    print("\n")

Nome do Pokémon: Geodude
Tipos do Pokémon: rock
Tipos do Pokémon: ground
Valor em against_grass 4.0


Nome do Pokémon: Graveler
Tipos do Pokémon: rock
Tipos do Pokémon: ground
Valor em against_grass 4.0


Nome do Pokémon: Golem
Tipos do Pokémon: rock
Tipos do Pokémon: ground
Valor em against_grass 4.0


Nome do Pokémon: Onix
Tipos do Pokémon: rock
Tipos do Pokémon: ground
Valor em against_grass 4.0

### Pokémons Fracos Contra o tipo Fogo

In [46]:

weakest_pokemon_top10 = df_pokemon["against_fire"].nlargest(4)

for idx in weakest_pokemon_top10.index:
    print("Nome do Pokémon:", df_pokemon.loc[idx, "english_name"])
    print("!° Primeiro Tipo:", df_pokemon.loc[idx, "primary_type"])
    print("2? Segundo Tipo:", df_pokemon.loc[idx, "secondary_type"])
    print("Valor em against_fire:", df_pokemon.loc[idx, "against_fire"])
    print("\n")

Nome do Pokémon: Paras
!° Primeiro Tipo: bug
2? Segundo Tipo: grass
Valor em against_fire: 4.0


Nome do Pokémon: Parasect
!° Primeiro Tipo: bug
2? Segundo Tipo: grass
Valor em against_fire: 4.0


Nome do Pokémon: Forretress
!° Primeiro Tipo: bug
2? Segundo Tipo: steel
Valor em against_fire: 4.0


Nome do Pokémon: Scizor
!° Primeiro Tipo: bug
2? Segundo Tipo: steel
Valor em against_fire: 4.0

In [45]:
fraquezas_fire_vs_grama = df_pokemon[df_pokemon['against_fire'] >= 4]
fraquezas_fire_vs_grama_sorted = fraquezas_fire_vs_grama.sort_values(by='against_fire', ascending=False)
display(fraquezas_fire_vs_grama_sorted[["english_name", "primary_type", "secondary_type","against_fire"]])

    english_name primary_type secondary_type  against_fire
45         Paras          bug          grass           4.0
46      Parasect          bug          grass           4.0
871         Snom          ice            bug           4.0
797      Kartana        grass          steel           4.0
648     Genesect          bug          steel           4.0
631       Durant          bug          steel           4.0
597   Ferrothorn        grass          steel           4.0
596    Ferroseed        grass          steel           4.0
588   Escavalier          bug          steel           4.0
541     Leavanny          bug          grass           4.0
540     Swadloon          bug          grass           4.0
539     Sewaddle          bug          grass           4.0
459    Abomasnow        grass            ice           4.0
458       Snover        grass            ice           4.0
412     Wormadam          bug          grass           4.0
211       Scizor          bug          steel           4.0
204   Forretress          bug          steel           4.0
872     Frosmoth          ice            bug           4.0

In [47]:

weakest_pokemon_top10 = df_pokemon[(df_pokemon['against_water' ]) & (df_pokemon['against_ground' ])].nlargest(4)
for idx in weakest_pokemon_top10.index:
    print("Nome do Pokémon:", df_pokemon.loc[idx, "english_name"])
    print("!° Primeiro Tipo:", df_pokemon.loc[idx, "primary_type"])
    print("2? Segundo Tipo:", df_pokemon.loc[idx, "secondary_type"])
    print("Valor em against_water:", df_pokemon.loc[idx, "against_water"])
    print("Valor em against_ground:", df_pokemon.loc[idx, "against_ground"])

    print("\n")

TypeError: unsupported operand type(s) for &: 'float' and 'float'