### Criando o ambiente para análise

In [5]:
import pandas as pd

### Explicação sobre a nomeclatura:
- Dataframe: Quadro de dados
- Dataset: Conjunto de dados

### Carregando os dados em xlsx

In [6]:
df_pokemon = pd.read_excel("pokemon.xlsx")
display(df_pokemon)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
0,1,I,Bulbasaur,Fushigidane,grass,poison,Seed Pokémon,88.14,11.86,0.7,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,There is a plant seed on its back right from t...
1,2,I,Ivysaur,Fushigisou,grass,poison,Seed Pokémon,88.14,11.86,1.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,"When the bulb on its back grows large, it appe..."
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...
3,4,I,Charmander,Hitokage,fire,NaN,Lizard Pokémon,88.14,11.86,0.6,...,Level,Charmeleon,Level,Charizard,NaN,NaN,NaN,NaN,NaN,It has a preference for hot things. When it ra...
4,5,I,Charmeleon,Lizardo,fire,NaN,Flame Pokémon,88.14,11.86,1.1,...,Level,Charmeleon,Level,Charizard,NaN,NaN,NaN,NaN,NaN,"It has a barbaric nature. In battle, it whips ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,894,VIII,Regieleki,Regieleki,electric,NaN,Electron Pokémon,NaN,NaN,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This Pokémon is a cluster of electrical energy...
894,895,VIII,Regidrago,Regidrago,dragon,NaN,Dragon Orb Pokémon,NaN,NaN,2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An academic theory proposes that Regidrago’s a...
895,896,VIII,Glastrier,Blizapos,ice,NaN,Wild Horse Pokémon,NaN,NaN,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Glastrier emits intense cold from its hooves. ...
896,897,VIII,Spectrier,Rayspos,ghost,NaN,Swift Horse Pokémon,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It probes its surroundings with all its senses...
897,898,VIII,Calyrex,Badrex,psychic,grass,King Pokémon,NaN,NaN,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Calyrex is a merciful Pokémon, capable of prov..."

### Método Head 
- Tem como objetivo : Mostrar os primeiros dados do dataframe
- Exemplo: df_nome.head() ou df_nome.head(5) -> Aqui mostrar os 5° primeiros dados do dataframe

In [9]:
df_pokemon.head(3)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
0,1,I,Bulbasaur,Fushigidane,grass,poison,Seed Pokémon,88.14,11.86,0.7,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,There is a plant seed on its back right from t...
1,2,I,Ivysaur,Fushigisou,grass,poison,Seed Pokémon,88.14,11.86,1.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,"When the bulb on its back grows large, it appe..."
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...

### Método Tail 
- Tem como objetivo : Mostrar últimos dados do dataframe
- Exemplo: df_nome.tail() ou df_nome.tail(5) -> Aqui mostra os últimos 5° dados do dataframe

In [8]:
df_pokemon.tail(3)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
895,896,VIII,Glastrier,Blizapos,ice,NaN,Wild Horse Pokémon,NaN,NaN,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Glastrier emits intense cold from its hooves. ...
896,897,VIII,Spectrier,Rayspos,ghost,NaN,Swift Horse Pokémon,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It probes its surroundings with all its senses...
897,898,VIII,Calyrex,Badrex,psychic,grass,King Pokémon,NaN,NaN,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Calyrex is a merciful Pokémon, capable of prov..."

### Método Sample
- Tem como objetivo : Mostrar dados misturado 
- Exemplo: df_nome.sample() ou df_nome.sample(5) -> Aqui mostra os 5° dados misturados do dataframe

In [7]:
df_pokemon.sample(3)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
809,810,VIII,Grookey,Sarunori,grass,NaN,Chimp Pokémon,88.14,11.86,0.3,...,Level,Thwackey,Level,Rillaboom,NaN,NaN,NaN,NaN,NaN,When it uses its special stick to strike up a ...
530,531,V,Audino,Tabunne,normal,NaN,Hearing Pokémon,50.2,49.8,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Audino,NaN,Audino’s sense of hearing is superb. Not even ...
465,466,IV,Electivire,Elekible,electric,NaN,Thunderbolt Pokémon,75.49,24.51,1.8,...,Level,Electabuzz,Trade with Electirizer,Electivire,NaN,NaN,NaN,NaN,NaN,The amount of electrical energy this Pokémon p...

### Métodos Info e describe 
 - Serve para dar uma visão geral nos dados que ainda não conhecemos

### Método Info 
- Tem como objetivo : Mostrar informações estatísticas
- Exemplo: df_nome.info()

In [15]:
df_pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 55 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   national_number     898 non-null    int64
 1   gen                 898 non-null    object
 2   english_name        898 non-null    object
 3   japanese_name       898 non-null    object
 4   primary_type        898 non-null    object
 5   secondary_type      469 non-null    object
 6   classification      898 non-null    object
 7   percent_male        776 non-null    object
 8   percent_female      776 non-null    object
 9   height_m            898 non-null    float64
 10  weight_kg           898 non-null    float64
 11  capture_rate        898 non-null    object
 12  base_egg_steps      898 non-null    int64
 13  hp                  898 non-null    int64
 14  attack              898 non-null    int64
 15  defense             898 non-null    int64
 16  sp_attack           898 non-null    int64
 17  sp_defense          898 non-null    int64
 18  speed               898 non-null    int64
 19  abilities_0         898 non-null    object
 20  abilities_1         495 non-null    object
 21  abilities_2         3 non-null      object
 22  abilities_hidden    763 non-null    object
 23  against_normal      898 non-null    float64
 24  against_fire        898 non-null    float64
 25  against_water       898 non-null    float64
 26  against_electric    898 non-null    float64
 27  against_grass       898 non-null    float64
 28  against_ice         898 non-null    float64
 29  against_fighting    898 non-null    float64
 30  against_poison      898 non-null    float64
 31  against_ground      898 non-null    float64
 32  against_flying      898 non-null    float64
 33  against_psychic     898 non-null    float64
 34  against_bug         898 non-null    float64
 35  against_rock        898 non-null    float64
 36  against_ghost       898 non-null    float64
 37  against_dragon      898 non-null    float64
 38  against_dark        898 non-null    float64
 39  against_steel       898 non-null    float64
 40  against_fairy       898 non-null    float64
 41  is_sublegendary     898 non-null    int64
 42  is_legendary        898 non-null    int64
 43  is_mythical         898 non-null    int64
 44  evochain_0          898 non-null    object
 45  evochain_1          728 non-null    object
 46  evochain_2          728 non-null    object
 47  evochain_3          335 non-null    object
 48  evochain_4          332 non-null    object
 49  evochain_5          19 non-null     object
 50  evochain_6          19 non-null     object
 51  gigantamax          31 non-null     object
 52  mega_evolution      46 non-null     object
 53  mega_evolution_alt  2 non-null      object
 54  description         898 non-null    object
dtypes: float64(20), int64(11), object(24)
memory usage: 386.0+ KB

### Método describe 
- Tem como objetivo : Resumo de informações estatísticas importantes 
- Exemplo: df_nome.describe()

In [59]:
df_pokemon.describe()

,national_number,height_m,weight_kg,base_egg_steps,hp,attack,defense,sp_attack,sp_defense,speed,...,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,is_sublegendary,is_legendary,is_mythical
count,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,...,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.00000,898.000000,898.000000,898.000000
mean,449.500000,1.185969,63.970045,7544.587973,69.031180,76.544543,71.886414,69.681514,69.876392,65.949889,...,0.999165,1.245546,0.994432,0.972717,1.057628,0.984131,1.08157,0.050111,0.022272,0.022272
std,259.374568,1.234222,119.430298,7101.313608,26.213707,29.665559,29.536184,29.372609,27.012142,28.456596,...,0.609120,0.702248,0.553163,0.365120,0.441639,0.497022,0.53157,0.218296,0.147648,0.147648
min,1.000000,0.100000,0.100000,1280.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,...,0.250000,0.250000,0.000000,0.000000,0.250000,0.250000,0.25000,0.000000,0.000000,0.000000
25%,225.250000,0.500000,8.500000,5120.000000,50.000000,55.000000,50.000000,46.250000,50.000000,45.000000,...,0.500000,1.000000,1.000000,1.000000,1.000000,0.500000,1.00000,0.000000,0.000000,0.000000
50%,449.500000,1.000000,27.000000,5120.000000,65.000000,75.000000,67.000000,65.000000,65.000000,65.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000
75%,673.750000,1.500000,65.000000,6400.000000,80.000000,95.000000,90.000000,90.000000,85.000000,85.000000,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000
max,898.000000,20.000000,999.900000,30720.000000,255.000000,181.000000,230.000000,173.000000,230.000000,200.000000,...,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,4.00000,1.000000,1.000000,1.000000

## Método Shape
- Tem como objetivo : Mostrar total de linhas e Colunas em um dataframe
- Exemplo: df_nome.shape

In [13]:
linhas, colunas = df_pokemon.shape
print(f"Podemos Observar que essa database tem um total de {linhas} linhas e um total de {colunas} colunas")

Podemos Observar que essa database tem um total de 898 linhas e um total de 55 colunas

### Selecionando subconjuntos do Dataframe
- Selecionando uma coluna específica

In [14]:
colums_type = df_pokemon["primary_type"]
display(colums_type)

0         grass
1         grass
2         grass
3          fire
4          fire
         ...
893    electric
894      dragon
895         ice
896       ghost
897     psychic
Name: primary_type, Length: 898, dtype: object

### Pegando o nome e o primeiro tipo

In [16]:
name_type_df_pokemon = df_pokemon[["english_name","primary_type"]]
display(name_type_df_pokemon)

    english_name primary_type
0      Bulbasaur        grass
1        Ivysaur        grass
2       Venusaur        grass
3     Charmander         fire
4     Charmeleon         fire
..           ...          ...
893    Regieleki     electric
894    Regidrago       dragon
895    Glastrier          ice
896    Spectrier        ghost
897      Calyrex      psychic

[898 rows x 2 columns]

### Pegando o nome , primeiro tipo e o segundo tipo

In [72]:
name_type_df_pokemon = df_pokemon[["english_name","primary_type", "secondary_type"]]
display(name_type_df_pokemon)

    english_name primary_type secondary_type
0      Bulbasaur        grass         poison
1        Ivysaur        grass         poison
2       Venusaur        grass         poison
3     Charmander         fire            NaN
4     Charmeleon         fire            NaN
..           ...          ...            ...
893    Regieleki     electric            NaN
894    Regidrago       dragon            NaN
895    Glastrier          ice            NaN
896    Spectrier        ghost            NaN
897      Calyrex      psychic          grass

[898 rows x 3 columns]

## Área de Estudo : Grama 🌱
### Pegando todos os pokémons com o primeiro tipo "grama" = 🌱

In [17]:
grass_df_pokemon = df_pokemon[df_pokemon["primary_type"]=="grass"]
display(grass_df_pokemon)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
0,1,I,Bulbasaur,Fushigidane,grass,poison,Seed Pokémon,88.14,11.86,0.7,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,There is a plant seed on its back right from t...
1,2,I,Ivysaur,Fushigisou,grass,poison,Seed Pokémon,88.14,11.86,1.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,"When the bulb on its back grows large, it appe..."
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...
42,43,I,Oddish,Nazonokusa,grass,poison,Weed Pokémon,50.2,49.8,0.5,...,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,"If exposed to moonlight, it starts to move. It..."
43,44,I,Gloom,Kusaihana,grass,poison,Weed Pokémon,50.2,49.8,0.8,...,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,Its pistils exude an incredibly foul odor. The...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,829,VIII,Gossifleur,Himenka,grass,NaN,Flowering Pokémon,50.2,49.8,0.4,...,Level,Eldegoss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It anchors itself in the ground with its singl...
829,830,VIII,Eldegoss,Watashiraga,grass,NaN,Cotton Bloom Pokémon,50.2,49.8,0.5,...,Level,Eldegoss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The seeds attached to its cotton fluff are ful...
839,840,VIII,Applin,Kajitchu,grass,dragon,Apple Core Pokémon,50.2,49.8,0.2,...,Use Tart Apple,Flapple,Use Sweet Apple,Appletun,NaN,NaN,NaN,NaN,NaN,It spends its entire life inside an apple. It ...
840,841,VIII,Flapple,Appryu,grass,dragon,Apple Wing Pokémon,50.2,49.8,0.3,...,Use Tart Apple,Flapple,Use Sweet Apple,Appletun,NaN,NaN,Gigantamax Flapple,NaN,NaN,"It ate a sour apple, and that induced its evol..."
841,842,VIII,Appletun,Tarupple,grass,dragon,Apple Nectar Pokémon,50.2,49.8,0.4,...,Use Tart Apple,Flapple,Use Sweet Apple,Appletun,NaN,NaN,NaN,NaN,NaN,Eating a sweet apple caused its evolution. A n...

In [33]:
grass_water_df_pokemon = df_pokemon[(df_pokemon["primary_type"] == "grass") & (df_pokemon["secondary_type"] == "water")]
display(grass_water_df_pokemon)

Empty DataFrame
Columns: [national_number, gen, english_name, japanese_name, primary_type, secondary_type, classification, percent_male, percent_female, height_m, weight_kg, capture_rate, base_egg_steps, hp, attack, defense, sp_attack, sp_defense, speed, abilities_0, abilities_1, abilities_2, abilities_hidden, against_normal, against_fire, against_water, against_electric, against_grass, against_ice, against_fighting, against_poison, against_ground, against_flying, against_psychic, against_bug, against_rock, against_ghost, against_dragon, against_dark, against_steel, against_fairy, is_sublegendary, is_legendary, is_mythical, evochain_0, evochain_1, evochain_2, evochain_3, evochain_4, evochain_5, evochain_6, gigantamax, mega_evolution, mega_evolution_alt, description]
Index: []

[0 rows x 55 columns]

## Pegando os pokémons do tipo Grama =🌱 e Venenoso = ☣️

In [24]:
grass_poison_df_pokemon = df_pokemon[(df_pokemon["primary_type"]=="grass") & (df_pokemon["secondary_type"]=="poison")]
display(grass_poison_df_pokemon)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
0,1,I,Bulbasaur,Fushigidane,grass,poison,Seed Pokémon,88.14,11.86,0.7,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,There is a plant seed on its back right from t...
1,2,I,Ivysaur,Fushigisou,grass,poison,Seed Pokémon,88.14,11.86,1.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,"When the bulb on its back grows large, it appe..."
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...
42,43,I,Oddish,Nazonokusa,grass,poison,Weed Pokémon,50.2,49.8,0.5,...,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,"If exposed to moonlight, it starts to move. It..."
43,44,I,Gloom,Kusaihana,grass,poison,Weed Pokémon,50.2,49.8,0.8,...,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,Its pistils exude an incredibly foul odor. The...
44,45,I,Vileplume,Ruffresia,grass,poison,Flower Pokémon,50.2,49.8,1.2,...,Level,Gloom,Use Leaf Stone,Vileplume,NaN,NaN,NaN,NaN,NaN,It has the world’s largest petals. With every ...
68,69,I,Bellsprout,Madatsubomi,grass,poison,Flower Pokémon,50,50,0.7,...,Level,Weepinbell,Use Leaf Stone,Victreebel,NaN,NaN,NaN,NaN,NaN,Prefers hot and humid places. It ensnares tiny...
69,70,I,Weepinbell,Utsudon,grass,poison,Flycatcher Pokémon,50,50,1.0,...,Level,Weepinbell,Use Leaf Stone,Victreebel,NaN,NaN,NaN,NaN,NaN,"When hungry, it swallows anything that moves. ..."
70,71,I,Victreebel,Utsubot,grass,poison,Flycatcher Pokémon,50,50,1.7,...,Level,Weepinbell,Use Leaf Stone,Victreebel,NaN,NaN,NaN,NaN,NaN,Lures prey with the sweet aroma of honey. Swal...
314,315,III,Roselia,Roselia,grass,poison,Thorn Pokémon,50.2,49.8,0.3,...,Level Up with Happiness Value at 220 During th...,Roselia,Use Shiny Stone,Roserade,NaN,NaN,NaN,NaN,NaN,Its flowers give off a relaxing fragrance. The...
405,406,IV,Budew,Subomie,grass,poison,Bud Pokémon,50.2,49.8,0.2,...,Level Up with Happiness Value at 220 During th...,Roselia,Use Shiny Stone,Roserade,NaN,NaN,NaN,NaN,NaN,The pollen it releases contains poison. If thi...
406,407,IV,Roserade,Roserade,grass,poison,Bouquet Pokémon,50.2,49.8,0.9,...,Level Up with Happiness Value at 220 During th...,Roselia,Use Shiny Stone,Roserade,NaN,NaN,NaN,NaN,NaN,After captivating opponents with its sweet sce...
589,590,V,Foongus,Tamagetake,grass,poison,Mushroom Pokémon,50.2,49.8,0.2,...,Level,Amoonguss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No one knows what the Poké Ball–like pattern o...
590,591,V,Amoonguss,Morobareru,grass,poison,Mushroom Pokémon,50.2,49.8,0.6,...,Level,Amoonguss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This Pokémon puffs poisonous spores at its foe...

## Pegando os pokémons do tipo Grama =🌱 e Dragão = 🐉

In [22]:
grass_drgon_df_pokemon = df_pokemon[(df_pokemon["primary_type"] == "grass") & (df_pokemon["secondary_type"] == "dragon")]
display(grass_drgon_df_pokemon)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
839,840,VIII,Applin,Kajitchu,grass,dragon,Apple Core Pokémon,50.2,49.8,0.2,...,Use Tart Apple,Flapple,Use Sweet Apple,Appletun,NaN,NaN,NaN,NaN,NaN,It spends its entire life inside an apple. It ...
840,841,VIII,Flapple,Appryu,grass,dragon,Apple Wing Pokémon,50.2,49.8,0.3,...,Use Tart Apple,Flapple,Use Sweet Apple,Appletun,NaN,NaN,Gigantamax Flapple,NaN,NaN,"It ate a sour apple, and that induced its evol..."
841,842,VIII,Appletun,Tarupple,grass,dragon,Apple Nectar Pokémon,50.2,49.8,0.4,...,Use Tart Apple,Flapple,Use Sweet Apple,Appletun,NaN,NaN,NaN,NaN,NaN,Eating a sweet apple caused its evolution. A n...

## Área de Estudo: Fogo 
## Pegandos todos os pokémons do primeiro tipo fire 🔥

In [25]:
fire_df_pokemon = df_pokemon[df_pokemon["primary_type"]=="fire"]
display(fire_df_pokemon)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
3,4,I,Charmander,Hitokage,fire,NaN,Lizard Pokémon,88.14,11.86,0.6,...,Level,Charmeleon,Level,Charizard,NaN,NaN,NaN,NaN,NaN,It has a preference for hot things. When it ra...
4,5,I,Charmeleon,Lizardo,fire,NaN,Flame Pokémon,88.14,11.86,1.1,...,Level,Charmeleon,Level,Charizard,NaN,NaN,NaN,NaN,NaN,"It has a barbaric nature. In battle, it whips ..."
5,6,I,Charizard,Lizardon,fire,flying,Flame Pokémon,88.14,11.86,1.7,...,Level,Charmeleon,Level,Charizard,NaN,NaN,Gigantamax Charizard,Mega Charizard X,Mega Charizard Y,It spits fire that is hot enough to melt bould...
36,37,I,Vulpix,Rokon,fire,ice,Fox Pokémon,24.9,75.1,0.6,...,Use Fire Stone,Ninetales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"While young, it has six gorgeous tails. When i..."
37,38,I,Ninetales,Kyukon,fire,ice,Fox Pokémon,24.9,75.1,1.1,...,Use Fire Stone,Ninetales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"It is said to live 1,000 years, and each of it..."
57,58,I,Growlithe,Gardie,fire,NaN,Puppy Pokémon,75.49,24.51,0.7,...,Use Fire Stone,Arcanine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It has a brave and trustworthy nature. It fear...
58,59,I,Arcanine,Windie,fire,NaN,Legendary Pokémon,75.49,24.51,1.9,...,Use Fire Stone,Arcanine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"The sight of it running over 6,200 miles in a ..."
76,77,I,Ponyta,Ponyta,fire,psychic,Fire Horse Pokémon,50.2,49.8,1.0,...,Level,Rapidash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It can’t run properly when it’s newly born. As...
77,78,I,Rapidash,Gallop,fire,psychic,Fire Horse Pokémon,50.2,49.8,1.7,...,Level,Rapidash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This Pokémon can be seen galloping through fie...
125,126,I,Magmar,Boober,fire,NaN,Spitfire Pokémon,75.49,24.51,1.3,...,Level,Magmar,Trade with Magmarizer,Magmortar,NaN,NaN,NaN,NaN,NaN,Magmar dispatches its prey with fire. But it r...
135,136,I,Flareon,Booster,fire,NaN,Flame Pokémon,88.14,11.86,0.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Once it has stored up enough heat, this Pokémo..."
145,146,I,Moltres,Fire,fire,flying,Flame Pokémon,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It’s one of the legendary bird Pokémon. When M...
154,155,II,Cyndaquil,Hinoarashi,fire,NaN,Fire Mouse Pokémon,88.1,11.9,0.5,...,Level,Quilava,Level,Typhlosion,NaN,NaN,NaN,NaN,NaN,Cyndaquil protects itself by flaring up the fl...
155,156,II,Quilava,Magmarashi,fire,NaN,Volcano Pokémon,88.1,11.9,0.9,...,Level,Quilava,Level,Typhlosion,NaN,NaN,NaN,NaN,NaN,Quilava keeps its foes at bay with the intensi...
156,157,II,Typhlosion,Bakphoon,fire,NaN,Volcano Pokémon,88.1,11.9,1.7,...,Level,Quilava,Level,Typhlosion,NaN,NaN,NaN,NaN,NaN,Typhlosion obscures itself behind a shimmering...
217,218,II,Slugma,Magmag,fire,NaN,Lava Pokémon,50,50,0.7,...,Level,Magcargo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Molten magma courses throughout Slugma’s circu...
218,219,II,Magcargo,Magcargot,fire,rock,Lava Pokémon,50,50,0.8,...,Level,Magcargo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Magcargo’s shell is actually its skin that har...
239,240,II,Magby,Buby,fire,NaN,Live Coal Pokémon,75.49,24.51,0.7,...,Level,Magmar,Trade with Magmarizer,Magmortar,NaN,NaN,NaN,NaN,NaN,This Pokémon is still small and timid. Wheneve...
243,244,II,Entei,Entei,fire,NaN,Volcano Pokémon,NaN,NaN,2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Entei embodies the passion of magma. This Poké...
249,250,II,Ho-Oh,Houou,fire,flying,Rainbow Pokémon,NaN,NaN,3.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ho-Oh’s feathers glow in seven colors dependin...
254,255,III,Torchic,Achamo,fire,NaN,Chick Pokémon,88.14,11.86,0.4,...,Level,Combusken,Level,Blaziken,NaN,NaN,NaN,NaN,NaN,"Torchic sticks with its Trainer, following beh..."
255,256,III,Combusken,Wakasyamo,fire,fighting,Young Fowl Pokémon,88.14,11.86,0.9,...,Level,Combusken,Level,Blaziken,NaN,NaN,NaN,NaN,NaN,Combusken toughens up its legs and thighs by r...
256,257,III,Blaziken,Bursyamo,fire,fighting,Blaze Pokémon,88.14,11.86,1.9,...,Level,Combusken,Level,Blaziken,NaN,NaN,NaN,Mega Blaziken,NaN,"In battle, Blaziken blows out intense flames f..."
321,322,III,Numel,Donmel,fire,ground,Numb Pokémon,50,50,0.7,...,Level,Camerupt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Numel is extremely dull witted—it doesn’t noti...
322,323,III,Camerupt,Bakuuda,fire,ground,Eruption Pokémon,50,50,1.9,...,Level,Camerupt,NaN,NaN,NaN,NaN,NaN,Mega Camerupt,NaN,Camerupt has a volcano inside its body. Magma ...
323,324,III,Torkoal,Cotoise,fire,NaN,Coal Pokémon,50.2,49.8,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It burns coal inside its shell for energy. It ...
389,390,IV,Chimchar,Hikozaru,fire,NaN,Chimp Pokémon,88.1,11.9,0.5,...,Level,Monferno,Level,Infernape,NaN,NaN,NaN,NaN,NaN,Its fiery rear end is fueled by gas made in it...
390,391,IV,Monferno,Moukazaru,fire,fighting,Playful Pokémon,88.1,11.9,0.9,...,Level,Monferno,Level,Infernape,NaN,NaN,NaN,NaN,NaN,It skillfully controls the intensity of the fi...
391,392,IV,Infernape,Goukazaru,fire,fighting,Flame Pokémon,88.1,11.9,1.2,...,Level,Monferno,Level,Infernape,NaN,NaN,NaN,NaN,NaN,Its crown of fire is indicative of its fiery n...
466,467,IV,Magmortar,Booburn,fire,NaN,Blast Pokémon,75.49,24.51,1.6,...,Level,Magmar,Trade with Magmarizer,Magmortar,NaN,NaN,NaN,NaN,NaN,"When Magmortar inhales deeply, the fire burnin..."
484,485,IV,Heatran,Heatran,fire,steel,Lava Dome Pokémon,50.2,49.8,1.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It dwells in volcanic caves. It digs in with i...
497,498,V,Tepig,Pokabu,fire,NaN,Fire Pig Pokémon,88.1,11.9,0.5,...,Level,Pignite,Level,Emboar,NaN,NaN,NaN,NaN,NaN,It can deftly dodge its foe’s attacks while sh...
498,499,V,Pignite,Chaoboo,fire,fighting,Fire Pig Pokémon,88.1,11.9,1.0,...,Level,Pignite,Level,Emboar,NaN,NaN,NaN,NaN,NaN,"The more it eats, the more fuel it has to make..."
499,500,V,Emboar,Enbuoh,fire,fighting,Mega Fire Pig Pokémon,88.1,11.9,1.6,...,Level,Pignite,Level,Emboar,NaN,NaN,NaN,NaN,NaN,It can throw a fire punch by setting its fists...
512,513,V,Pansear,Baoppu,fire,NaN,High Temp Pokémon,88.1,11.9,0.6,...,Use Fire Stone,Simisear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Very intelligent, it roasts berries before eat..."
513,514,V,Simisear,Baokkie,fire,NaN,Ember Pokémon,88.1,11.9,1.0,...,Use Fire Stone,Simisear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A flame burns inside its body. It scatters emb...
553,554,V,Darumaka,Darumakka,fire,ice,Zen Charm Pokémon,50.2,49.8,0.6,...,Level,Darmanitan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It derives its power from fire burning inside ...
554,555,V,Darmanitan,Hihidaruma,fire,fire,Blazing Pokémon,50.2,49.8,1.3,...,Level,Darmanitan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The thick arms of this hot-blooded Pokémon can...
630,631,V,Heatmor,Kuitaran,fire,NaN,Anteater Pokémon,50.2,49.8,1.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,There’s a hole in its tail that allows it to d...
652,653,VI,Fennekin,Fokko,fire,NaN,Fox Pokémon,88.1,11.9,0.4,...,Level,Braixen,Level,Delphox,NaN,NaN,NaN,NaN,NaN,"Eating a twig fills it with energy, and its ro..."
653,654,VI,Braixen,Tairenar,fire,NaN,Fox Pokémon,88.1,11.9,1.0,...,Level,Braixen,Level,Delphox,NaN,NaN,NaN,NaN,NaN,It has a twig stuck in its tail. With friction...
654,655,VI,Delphox,Mahoxy,fire,psychic,Fox Pokémon,88.1,11.9,1.5,...,Level,Braixen,Level,Delphox,NaN,NaN,NaN,NaN,NaN,It gazes into the flame at the tip of its bran...
661,662,VI,Fletchinder,Hinoyakoma,fire,flying,Ember Pokémon,50.2,49.8,0.7,...,Level,Fletchinder,Level,Talonflame,NaN,NaN,NaN,NaN,NaN,Fletchinder launches embers into the den of it...
662,663,VI,Talonflame,Fiarrow,fire,flying,Scorching Pokémon,50.2,49.8,1.2,...,Level,Fletchinder,Level,Talonflame,NaN,NaN,NaN,NaN,NaN,Talonflame mainly preys upon other bird Pokémo...
666,667,VI,Litleo,Shishiko,fire,normal,Lion Cub Pokémon,11.2,88.8,0.6,...,Level,Pyroar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"When they’re young, they live with a pride. On..."
667,668,VI,Pyroar,Kaenjishi,fire,normal,Royal Pokémon,11.2,88.8,1.5,...,Level,Pyroar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"The males are usually lazy, but when attacked ..."
720,721,VI,Volcanion,Volcanion,fire,water,Steam Pokémon,NaN,NaN,1.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It lets out billows of steam and disappears in...
724,725,VII,Litten,Nyabby,fire,NaN,Fire Cat Pokémon,88.14,11.86,0.4,...,Level,Torracat,Level,Incineroar,NaN,NaN,NaN,NaN,NaN,"If you try too hard to get close to it, it won..."
725,726,VII,Torracat,Nyaheat,fire,NaN,Fire Cat Pokémon,88.14,11.86,0.7,...,Level,Torracat,Level,Incineroar,NaN,NaN,NaN,NaN,NaN,It can act spoiled if it grows close to its Tr...
726,727,VII,Incineroar,Gaogaen,fire,dark,Heel Pokémon,88.14,11.86,1.8,...,Level,Torracat,Level,Incineroar,NaN,NaN,NaN,NaN,NaN,"Although it’s rough mannered and egotistical, ..."
740,741,VII,Oricorio,Odoridori,fire,flying,Dancing Pokémon,24.6,75.4,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It wins the hearts of its enemies with its pas...
775,776,VII,Turtonator,Bakugames,fire,dragon,Blast Turtle Pokémon,50.2,49.8,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosive substances coat the shell on its bac...
805,806,VII,Blacephalon,Zugadon,fire,ghost,Fireworks Pokémon,NaN,NaN,1.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"It slithers toward people. Then, without warni..."
812,813,VIII,Scorbunny,Hibanny,fire,NaN,Rabbit Pokémon,88.14,11.86,0.3,...,Level,Raboot,Level,Cinderace,NaN,NaN,NaN,NaN,NaN,A warm-up of running around gets fire energy c...
813,814,VIII,Raboot,Rabbifoot,fire,NaN,Rabbit Pokémon,88.14,11.86,0.6,...,Level,Raboot,Level,Cinderace,NaN,NaN,NaN,NaN,NaN,Its thick and fluffy fur protects it from the ...
814,815,VIII,Cinderace,Aceburn,fire,NaN,Striker Pokémon,88.14,11.86,1.4,...,Level,Raboot,Level,Cinderace,NaN,NaN,Gigantamax Cinderace,NaN,NaN,"It juggles a pebble with its feet, turning it ..."
849,850,VIII,Sizzlipede,Yakuda,fire,bug,Radiator Pokémon,50.2,49.8,0.7,...,Level,Centiskorch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It stores flammable gas in its body and uses i...
850,851,VIII,Centiskorch,Maruyakude,fire,bug,Radiator Pokémon,50.2,49.8,3.0,...,Level,Centiskorch,NaN,NaN,NaN,NaN,Gigantamax Centiskorch,NaN,NaN,"When it heats up, its body temperature reaches..."

## Pegando os pokémons do tipo Fire = 🔥 e Grama = 🌱

In [30]:
fire_grass_df_pokemon = df_pokemon[(df_pokemon["primary_type"]=="fire") & (df_pokemon["primary_type"]=="grass")]
display(fire_grass_df_pokemon)
print(f"Podemos analisar que não existe ainda pokémnos de tipo fogo e grama ao mesmo tempo")

Empty DataFrame
Columns: [national_number, gen, english_name, japanese_name, primary_type, secondary_type, classification, percent_male, percent_female, height_m, weight_kg, capture_rate, base_egg_steps, hp, attack, defense, sp_attack, sp_defense, speed, abilities_0, abilities_1, abilities_2, abilities_hidden, against_normal, against_fire, against_water, against_electric, against_grass, against_ice, against_fighting, against_poison, against_ground, against_flying, against_psychic, against_bug, against_rock, against_ghost, against_dragon, against_dark, against_steel, against_fairy, is_sublegendary, is_legendary, is_mythical, evochain_0, evochain_1, evochain_2, evochain_3, evochain_4, evochain_5, evochain_6, gigantamax, mega_evolution, mega_evolution_alt, description]
Index: []

[0 rows x 55 columns]

Podemos analisar que não existe ainda pokémnos de tipo fogo e grama ao mesmo tempo

## Pegando os pokémons do tipo Fire = 🔥 e Água = 💧

In [36]:
fire_water_df_pokemon = df_pokemon[(df_pokemon["primary_type"]=="fire") & (df_pokemon["secondary_type"]=="water")]
display(fire_water_df_pokemon)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
720,721,VI,Volcanion,Volcanion,fire,water,Steam Pokémon,NaN,NaN,1.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It lets out billows of steam and disappears in...

## Pegando os pokémons do tipo Fire = 🔥 e Venenoso =

In [38]:
fire__poison_df_pokemon = df_pokemon[(df_pokemon["primary_type"]=="fire") & (df_pokemon["secondary_type"]=="poison")]
display(fire__poison_df_pokemon)
print(f"Podemos analisar que não exist nenhum pokémon com o primeiro tipo fogo com um segundo tipo venenoso")

Empty DataFrame
Columns: [national_number, gen, english_name, japanese_name, primary_type, secondary_type, classification, percent_male, percent_female, height_m, weight_kg, capture_rate, base_egg_steps, hp, attack, defense, sp_attack, sp_defense, speed, abilities_0, abilities_1, abilities_2, abilities_hidden, against_normal, against_fire, against_water, against_electric, against_grass, against_ice, against_fighting, against_poison, against_ground, against_flying, against_psychic, against_bug, against_rock, against_ghost, against_dragon, against_dark, against_steel, against_fairy, is_sublegendary, is_legendary, is_mythical, evochain_0, evochain_1, evochain_2, evochain_3, evochain_4, evochain_5, evochain_6, gigantamax, mega_evolution, mega_evolution_alt, description]
Index: []

[0 rows x 55 columns]

Podemos analisar que não exist nenhum pokémon com o primeiro tipo fogo com um segundo tipo venenoso

## Pegando os pokémons do tipo Fire = 🔥 e Elétrico =

In [45]:
fire_eletric_df_pokemon = df_pokemon[(df_pokemon["primary_type"]=="fire") & (df_pokemon["secondary_type"]=="eletric")]
display(fire_eletric_df_pokemon)
print(f"Pegando os pokémons do tipo Fire = 🔥 e Elétrico = Podemos analisar que não existe nenhum pokémon com o primeiro tipo fogo com um segundo tipo elétrico")

Empty DataFrame
Columns: [national_number, gen, english_name, japanese_name, primary_type, secondary_type, classification, percent_male, percent_female, height_m, weight_kg, capture_rate, base_egg_steps, hp, attack, defense, sp_attack, sp_defense, speed, abilities_0, abilities_1, abilities_2, abilities_hidden, against_normal, against_fire, against_water, against_electric, against_grass, against_ice, against_fighting, against_poison, against_ground, against_flying, against_psychic, against_bug, against_rock, against_ghost, against_dragon, against_dark, against_steel, against_fairy, is_sublegendary, is_legendary, is_mythical, evochain_0, evochain_1, evochain_2, evochain_3, evochain_4, evochain_5, evochain_6, gigantamax, mega_evolution, mega_evolution_alt, description]
Index: []

[0 rows x 55 columns]

Pegando os pokémons do tipo Fire = 🔥 e Elétrico = Podemos analisar que não existe nenhum pokémon com o primeiro tipo fogo com um segundo tipo elétrico

## Pegando os pokémons do tipo Fire = 🔥 e Dragão = 🐉

In [41]:
fire_dragon_df_pokemon = df_pokemon[(df_pokemon["primary_type"]=="fire") & (df_pokemon["secondary_type"]=="dragon")]
display(fire_dragon_df_pokemon)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
775,776,VII,Turtonator,Bakugames,fire,dragon,Blast Turtle Pokémon,50.2,49.8,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosive substances coat the shell on its bac...

## Pegando os pokémons por Geração e Tipo Venenoso

In [51]:
gen_poison_df_pokemon = df_pokemon[(df_pokemon["gen"] == "I") & (df_pokemon["primary_type"] == "poison")]
display(gen_poison_df_pokemon)
linhas, colunas= gen_poison_df_pokemon.shape
print(f"Geração I existem um total de {linhas} pokémons venososos")

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
22,23,I,Ekans,Arbo,poison,NaN,Snake Pokémon,50,50,2.0,...,Level,Arbok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"The older it gets, the longer it grows. At nig..."
23,24,I,Arbok,Arbok,poison,NaN,Cobra Pokémon,50,50,3.5,...,Level,Arbok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The frightening patterns on its belly have bee...
28,29,I,Nidoran♀,Nidoran♀,poison,NaN,Poison Pin Pokémon,0,100,0.4,...,When Female,Nidoran♀,Level 16,Nidorina,Use Moonstone,Nidoqueen,NaN,NaN,NaN,Females are more sensitive to smells than male...
29,30,I,Nidorina,Nidorina,poison,NaN,Poison Pin Pokémon,0,100,0.8,...,When Female,Nidoran♀,Level 16,Nidorina,Use Moonstone,Nidoqueen,NaN,NaN,NaN,The horn on its head has atrophied. It’s thoug...
30,31,I,Nidoqueen,Nidoqueen,poison,ground,Drill Pokémon,0,100,1.3,...,When Female,Nidoran♀,Level 16,Nidorina,Use Moonstone,Nidoqueen,NaN,NaN,NaN,Nidoqueen is better at defense than offense. W...
31,32,I,Nidoran♂,Nidoran♂,poison,NaN,Poison Pin Pokémon,100,0,0.5,...,When Male,Nidoran♂,Level 16,Nidorino,Use Moonstone,Nidoking,NaN,NaN,NaN,The horn on a male Nidoran’s forehead contains...
32,33,I,Nidorino,Nidorino,poison,NaN,Poison Pin Pokémon,100,0,0.9,...,When Male,Nidoran♂,Level 16,Nidorino,Use Moonstone,Nidoking,NaN,NaN,NaN,"With a horn that’s harder than diamond, this P..."
33,34,I,Nidoking,Nidoking,poison,ground,Drill Pokémon,100,0,1.4,...,When Male,Nidoran♂,Level 16,Nidorino,Use Moonstone,Nidoking,NaN,NaN,NaN,"When it goes on a rampage, it’s impossible to ..."
40,41,I,Zubat,Zubat,poison,flying,Bat Pokémon,50.2,49.8,0.8,...,Level,Golbat,Level Up with Happiness Value at 220,Crobat,NaN,NaN,NaN,NaN,NaN,It emits ultrasonic waves from its mouth to ch...
41,42,I,Golbat,Golbat,poison,flying,Bat Pokémon,50.2,49.8,1.6,...,Level,Golbat,Level Up with Happiness Value at 220,Crobat,NaN,NaN,NaN,NaN,NaN,It loves to drink other creatures’ blood. It’s...
87,88,I,Grimer,Betbeter,poison,poison,Sludge Pokémon,50,50,0.9,...,Level,Muk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Made of congealed sludge. It smells too putrid...
88,89,I,Muk,Betbeton,poison,poison,Sludge Pokémon,50,50,1.2,...,Level,Muk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Smells so awful, it can cause fainting. Throug..."
108,109,I,Koffing,Dogars,poison,NaN,Poison Gas Pokémon,50.2,49.8,0.6,...,Level,Weezing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Its body is full of poisonous gas. It floats i...
109,110,I,Weezing,Matadogas,poison,poison,Poison Gas Pokémon,50.2,49.8,1.2,...,Level,Weezing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It mixes gases between its two bodies. It’s sa...

Geração I existem um total de 14 pokémons venososos

##

In [93]:
grass_df_pokemon = df_pokemon[(df_pokemon["gen"] == "I") & (df_pokemon["primary_type"] == "grass") & (df_pokemon["secondary_type"] == "poison")]
display(grass_df_pokemon)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
0,1,I,Bulbasaur,Fushigidane,grass,poison,Seed Pokémon,88.14,11.86,0.7,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,There is a plant seed on its back right from t...
1,2,I,Ivysaur,Fushigisou,grass,poison,Seed Pokémon,88.14,11.86,1.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,"When the bulb on its back grows large, it appe..."
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...
42,43,I,Oddish,Nazonokusa,grass,poison,Weed Pokémon,50.2,49.8,0.5,...,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,"If exposed to moonlight, it starts to move. It..."
43,44,I,Gloom,Kusaihana,grass,poison,Weed Pokémon,50.2,49.8,0.8,...,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,Its pistils exude an incredibly foul odor. The...
44,45,I,Vileplume,Ruffresia,grass,poison,Flower Pokémon,50.2,49.8,1.2,...,Level,Gloom,Use Leaf Stone,Vileplume,NaN,NaN,NaN,NaN,NaN,It has the world’s largest petals. With every ...
68,69,I,Bellsprout,Madatsubomi,grass,poison,Flower Pokémon,50,50,0.7,...,Level,Weepinbell,Use Leaf Stone,Victreebel,NaN,NaN,NaN,NaN,NaN,Prefers hot and humid places. It ensnares tiny...
69,70,I,Weepinbell,Utsudon,grass,poison,Flycatcher Pokémon,50,50,1.0,...,Level,Weepinbell,Use Leaf Stone,Victreebel,NaN,NaN,NaN,NaN,NaN,"When hungry, it swallows anything that moves. ..."
70,71,I,Victreebel,Utsubot,grass,poison,Flycatcher Pokémon,50,50,1.7,...,Level,Weepinbell,Use Leaf Stone,Victreebel,NaN,NaN,NaN,NaN,NaN,Lures prey with the sweet aroma of honey. Swal...

In [96]:
weakness_df_pokemon = df_pokemon[['english_name','primary_type','against_water']]
weakness_df_pokemon

    english_name primary_type  against_water
0      Bulbasaur        grass            0.5
1        Ivysaur        grass            0.5
2       Venusaur        grass            0.5
3     Charmander         fire            2.0
4     Charmeleon         fire            2.0
..           ...          ...            ...
893    Regieleki     electric            1.0
894    Regidrago       dragon            0.5
895    Glastrier          ice            1.0
896    Spectrier        ghost            1.0
897      Calyrex      psychic            0.5

[898 rows x 3 columns]

In [103]:
weakness_df_pokemon = df_pokemon[df_pokemon['against_water' ] > 1]
weakness_df_pokemon[["english_name","primary_type","against_water"]]

    english_name primary_type  against_water
3     Charmander         fire            2.0
4     Charmeleon         fire            2.0
5      Charizard         fire            2.0
26     Sandshrew       ground            2.0
27     Sandslash       ground            2.0
..           ...          ...            ...
843   Sandaconda       ground            2.0
849   Sizzlipede         fire            2.0
850  Centiskorch         fire            2.0
866    Runerigus       ground            2.0
873  Stonjourner         rock            2.0

[155 rows x 3 columns]

In [104]:
weakness_df_pokemon = df_pokemon[(df_pokemon['against_water' ] > 2) & (df_pokemon['against_ground' ] > 2)]
weakness_df_pokemon[["english_name","primary_type","against_water","against_ground"]]

    english_name primary_type  against_water  against_ground
218     Magcargo         fire            4.0             4.0
837       Carkol         rock            4.0             4.0
838    Coalossal         rock            4.0             4.0

In [3]:
weakness_df_pokemon = df_pokemon[(df_pokemon['against_water' ] > 2) & (df_pokemon['against_ground' ] > 2)]
weakness_df_pokemon[["english_name","primary_type","secondary_type","against_water","against_ground"]]

    english_name primary_type secondary_type  against_water  against_ground
218     Magcargo         fire           rock            4.0             4.0
837       Carkol         rock           fire            4.0             4.0
838    Coalossal         rock           fire            4.0             4.0

In [8]:
mega_evolution_df_pokemon = df_pokemon[['english_name','mega_evolution']]
mega_evolution_df_pokemon

    english_name mega_evolution
0      Bulbasaur            NaN
1        Ivysaur            NaN
2       Venusaur  Mega Venusaur
3     Charmander            NaN
4     Charmeleon            NaN
..           ...            ...
893    Regieleki            NaN
894    Regidrago            NaN
895    Glastrier            NaN
896    Spectrier            NaN
897      Calyrex            NaN

[898 rows x 2 columns]

In [10]:
mega_evolution_df_pokemon = df_pokemon[df_pokemon['mega_evolution'].notna()]
mega_evolution_df_pokemon

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...
5,6,I,Charizard,Lizardon,fire,flying,Flame Pokémon,88.14,11.86,1.7,...,Level,Charmeleon,Level,Charizard,NaN,NaN,Gigantamax Charizard,Mega Charizard X,Mega Charizard Y,It spits fire that is hot enough to melt bould...
8,9,I,Blastoise,Kamex,water,NaN,Shellfish Pokémon,88.14,11.86,1.6,...,Level,Wartortle,Level,Blastoise,NaN,NaN,Gigantamax Blastoise,Mega Blastoise,NaN,It crushes its foe under its heavy body to cau...
14,15,I,Beedrill,Spear,bug,poison,Poison Bee Pokémon,50,50,1.0,...,Level,Kakuna,Level,Beedrill,NaN,NaN,NaN,Mega Beedrill,NaN,It has three poisonous stingers on its foreleg...
17,18,I,Pidgeot,Pigeot,normal,flying,Bird Pokémon,50,50,1.5,...,Level,Pidgeotto,Level,Pidgeot,NaN,NaN,NaN,Mega Pidgeot,NaN,"This Pokémon flies at Mach 2 speed, seeking pr..."
64,65,I,Alakazam,Foodin,psychic,NaN,Psi Pokémon,75.49,24.51,1.5,...,Level,Kadabra,Trade,Alakazam,NaN,NaN,NaN,Mega Alakazam,NaN,It has an incredibly high level of intelligenc...
79,80,I,Slowbro,Yadoran,water,psychic,Hermit Crab Pokémon,50.2,49.8,1.6,...,Level,Slowbro,Trade with King's Rock,Slowking,Slowpoke,Use Galarica Cuff,NaN,Mega Slowbro,NaN,Slowpoke became Slowbro when a Shellder bit on...
93,94,I,Gengar,Gangar,ghost,poison,Shadow Pokémon,50.2,49.8,1.5,...,Level,Haunter,Trade,Gengar,NaN,NaN,Gigantamax Gengar,Mega Gengar,NaN,"On the night of a full moon, if shadows move o..."
114,115,I,Kangaskhan,Garura,normal,NaN,Parent Pokémon,0,100,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Kangaskhan,NaN,Although it’s carrying its baby in a pouch on ...
126,127,I,Pinsir,Kailios,bug,NaN,Stagbeetle Pokémon,50.2,49.8,1.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Pinsir,NaN,These Pokémon judge one another based on pince...
129,130,I,Gyarados,Gyarados,water,flying,Atrocious Pokémon,50.2,49.8,6.5,...,Level,Gyarados,NaN,NaN,NaN,NaN,NaN,Mega Gyarados,NaN,It has an extremely aggressive nature. The Hyp...
141,142,I,Aerodactyl,Ptera,rock,flying,Fossil Pokémon,88.14,11.86,1.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Aerodactyl,NaN,This is a ferocious Pokémon from ancient times...
149,150,I,Mewtwo,Mewtwo,psychic,NaN,Genetic Pokémon,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Mewtwo X,Mega Mewtwo Y,"Its DNA is almost the same as Mew’s. However, ..."
180,181,II,Ampharos,Denryu,electric,NaN,Light Pokémon,50,50,1.4,...,Level,Flaaffy,Level,Ampharos,NaN,NaN,NaN,Mega Ampharos,NaN,The light from its tail can be seen from space...
207,208,II,Steelix,Haganeil,steel,ground,Iron Snake Pokémon,50.2,49.8,9.2,...,Trade with Metal Coat,Steelix,NaN,NaN,NaN,NaN,NaN,Mega Steelix,NaN,It is said that if an Onix lives for over 100 ...
211,212,II,Scizor,Hassam,bug,steel,Pincer Pokémon,50.2,49.8,1.8,...,Trade with Metal Coat,Scizor,NaN,NaN,NaN,NaN,NaN,Mega Scizor,NaN,Bulky pincers account for one third of Scizor’...
213,214,II,Heracross,Heracros,bug,fighting,Singlehorn Pokémon,50.2,49.8,1.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Heracross,NaN,Heracross loves sweet sap and will go looking ...
228,229,II,Houndoom,Hellgar,dark,fire,Dark Pokémon,50,50,1.4,...,Level,Houndoom,NaN,NaN,NaN,NaN,NaN,Mega Houndoom,NaN,They spew flames mixed with poison to finish o...
247,248,II,Tyranitar,Bangiras,rock,dark,Armor Pokémon,50.2,49.8,2.0,...,Level,Pupitar,Level,Tyranitar,NaN,NaN,NaN,Mega Tyranitar,NaN,Its body can’t be harmed by any sort of attack...
253,254,III,Sceptile,Jukain,grass,NaN,Forest Pokémon,88.14,11.86,1.7,...,Level,Grovyle,Level,Sceptile,NaN,NaN,NaN,Mega Sceptile,NaN,The leaves growing on Sceptile’s body are very...
256,257,III,Blaziken,Bursyamo,fire,fighting,Blaze Pokémon,88.14,11.86,1.9,...,Level,Combusken,Level,Blaziken,NaN,NaN,NaN,Mega Blaziken,NaN,"In battle, Blaziken blows out intense flames f..."
259,260,III,Swampert,Laglarge,water,ground,Mud Fish Pokémon,88.14,11.86,1.5,...,Level,Marshtomp,Level,Swampert,NaN,NaN,NaN,Mega Swampert,NaN,Swampert is very strong. It has enough power t...
281,282,III,Gardevoir,Sirnight,psychic,fairy,Embrace Pokémon,50.2,49.8,1.6,...,Level,Kirlia,Level,Gardevoir,NaN,NaN,NaN,Mega Gardevoir,NaN,It has the power to predict the future. Its po...
301,302,III,Sableye,Yamirami,dark,ghost,Darkness Pokémon,50.2,49.8,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Sableye,NaN,This Pokémon is feared. When its gemstone eyes...
302,303,III,Mawile,Kucheat,steel,fairy,Deceiver Pokémon,50.2,49.8,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Mawile,NaN,It uses its docile-looking face to lull foes i...
305,306,III,Aggron,Bossgodora,steel,rock,Iron Armor Pokémon,50.2,49.8,2.1,...,Level,Lairon,Level,Aggron,NaN,NaN,NaN,Mega Aggron,NaN,Aggron has a horn sharp enough to perforate th...
307,308,III,Medicham,Charem,fighting,psychic,Meditate Pokémon,50,50,1.3,...,Level,Medicham,NaN,NaN,NaN,NaN,NaN,Mega Medicham,NaN,"It is said that through meditation, Medicham h..."
309,310,III,Manectric,Livolt,electric,NaN,Discharge Pokémon,50.2,49.8,1.5,...,Level,Manectric,NaN,NaN,NaN,NaN,NaN,Mega Manectric,NaN,It stimulates its own muscles with electricity...
318,319,III,Sharpedo,Samehader,water,dark,Brutal Pokémon,50.2,49.8,1.8,...,Level,Sharpedo,NaN,NaN,NaN,NaN,NaN,Mega Sharpedo,NaN,"As soon as it catches the scent of prey, Sharp..."
322,323,III,Camerupt,Bakuuda,fire,ground,Eruption Pokémon,50,50,1.9,...,Level,Camerupt,NaN,NaN,NaN,NaN,NaN,Mega Camerupt,NaN,Camerupt has a volcano inside its body. Magma ...
333,334,III,Altaria,Tyltalis,dragon,flying,Humming Pokémon,50.2,49.8,1.1,...,Level,Altaria,NaN,NaN,NaN,NaN,NaN,Mega Altaria,NaN,"As it flies in a calm and relaxed manner, Alta..."
353,354,III,Banette,Juppeta,ghost,NaN,Marionette Pokémon,50,50,1.1,...,Level,Banette,NaN,NaN,NaN,NaN,NaN,Mega Banette,NaN,It’s a stuffed toy that was thrown away and be...
358,359,III,Absol,Absol,dark,NaN,Disaster Pokémon,50.2,49.8,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Absol,NaN,"Swift as the wind, Absol races through fields ..."
361,362,III,Glalie,Onigohri,ice,NaN,Face Pokémon,50.2,49.8,1.5,...,Level,Glalie,"On Female Pokémon, use Dawn Stone",Froslass,NaN,NaN,NaN,Mega Glalie,NaN,"It has a body of ice that won’t melt, even wit..."
372,373,III,Salamence,Bohmander,dragon,flying,Dragon Pokémon,50.2,49.8,1.5,...,Level,Shelgon,Level,Salamence,NaN,NaN,NaN,Mega Salamence,NaN,Salamence is an unusual Pokémon in that it was...
375,376,III,Metagross,Metagross,steel,psychic,Iron Leg Pokémon,NaN,NaN,1.6,...,Level,Metang,Level,Metagross,NaN,NaN,NaN,Mega Metagross,NaN,Because the magnetic powers of these Pokémon g...
379,380,III,Latias,Latias,dragon,psychic,Eon Pokémon,0,100,1.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Latias,NaN,Latias is highly sensitive to the emotions of ...
380,381,III,Latios,Latios,dragon,psychic,Eon Pokémon,100,0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Latios,NaN,Latios has the ability to make others see an i...
383,384,III,Rayquaza,Rayquaza,dragon,flying,Sky High Pokémon,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Rayquaza,NaN,Rayquaza is said to have lived for hundreds of...
427,428,IV,Lopunny,Mimilop,normal,NaN,Rabbit Pokémon,50.2,49.8,1.2,...,Level Up with Happiness Value at 220,Lopunny,NaN,NaN,NaN,NaN,NaN,Mega Lopunny,NaN,Lopunny is constantly monitoring its surroundi...
444,445,IV,Garchomp,Gaburias,dragon,ground,Mach Pokémon,50.2,49.8,1.9,...,Level,Gabite,Level,Garchomp,NaN,NaN,NaN,Mega Garchomp,NaN,Garchomp makes its home in volcanic mountains....
447,448,IV,Lucario,Lucario,fighting,steel,Aura Pokémon,88.14,11.86,1.2,...,Level Up with Happiness Value at 220 During th...,Lucario,NaN,NaN,NaN,NaN,NaN,Mega Lucario,NaN,"It controls waves known as auras, which are po..."
459,460,IV,Abomasnow,Yukinooh,grass,ice,Frosted Tree Pokémon,50.2,49.8,2.2,...,Level,Abomasnow,NaN,NaN,NaN,NaN,NaN,Mega Abomasnow,NaN,If it sees any packs of Darumaka going after S...
474,475,IV,Gallade,Erureido,psychic,fighting,Blade Pokémon,100,0,1.6,...,Level,Kirlia,"On Male Pokémon, use Dawn Stone",Gallade,NaN,NaN,NaN,Mega Gallade,NaN,"True to its honorable-warrior image, it uses t..."
530,531,V,Audino,Tabunne,normal,NaN,Hearing Pokémon,50.2,49.8,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Audino,NaN,Audino’s sense of hearing is superb. Not even ...
718,719,VI,Diancie,Diancie,rock,fairy,Jewel Pokémon,NaN,NaN,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Diancie,NaN,"A sudden transformation of Carbink, its pink, ..."